server:
  port: ${server.port}
spring:
  config:
    import: file:./config/application-external.yml
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FEE_DEV
    password: FEE_DEV
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cache:
      channel:
        size: ${rabbitmq.channel.size}
        checkout-timeout: ${rabbitmq.channel.checkout-timeout}ms
      connection:
        mode: ${rabbitmq.connection.mode}
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: ${redis.pool.max-active}
          max-idle: ${redis.pool.max-idle}
          min-idle: ${redis.pool.min-idle}
          max-wait: ${redis.pool.max-wait}ms
