server:
  port: 8082
redis:
  pool:
    max-active: 25
    max-idle: 10
    min-idle: 5
    max-wait: 3000
rabbitmq:
  channel:
    size: 25
    checkout-timeout: 1000
  connection:
    mode: channel

