server:
  port: 8082
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FEE_DEV
    password: FEE_DEV
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cache:
      channel:
        size: 25
        checkout-timeout: 1000ms
      connection:
        mode: channel
  data:
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-active: 25
          max-idle: 10
          min-idle: 5
          max-wait: 3000ms
