server:
  port: 8082
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: FEE_DEV
    password: FEE_DEV
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
